### ISSUE TITLE
Suggested addition with ink-tools

### ISSUE THREAD

**Issue by v20100v** [inkle/ink-library#10]
Hello,

I have a proposal to add it to your ink library : https://github.com/v20100v/ink-tools

I make this tool (CLI application in node.js) in order to compile inkle's story Ink file into JSON, with a watching mode. It uses the binary inklecate. It was designed in order to facilitate story integration wiht inkjs, and to consume JSON into a web application (SPA, React, Angular ...)

Bye.

**Comment by joethephish** [comment]
Thanks, [added](https://github.com/inkle/ink-library/commit/07168a1f17fbaee9bb8af312e9244e393a4a21c0)!
